pin save firestore added
f-lab-edu/pins pull request #14
Opened 2023-11-08 07:27 UTC by MojitoBar

2023-11-13 08:51 UTC, f-lab-jercy requested changes

2023-11-13 08:51 UTC, f-lab-jercy commented on pins/Extension/Date.swift
> +    func now() -> String {
now라는 함수명을 사용하고 있는데, 안의 내용은 지금 날짜를 반환하는게 아닌 date self값을 포맷팅한것으로 보입니다. 그렇기에 함수명을 다르게 변경해보는것도 좋을것 같습니다.

2023-11-13 08:51 UTC, f-lab-jercy commented on pins/Extension/UITextView.swift
> +extension UITextView {
UITextView를 확장하면 모든 UITextView인스턴스에 영향을 미칩니다. 현재 코드는 모든 코드에 다 영향을 끼치기에 프로토콜과 같은 형태로 만드는것이 더 좋을것 같습니다.
특히나 지금은 NotificationCenter로 모든곳에 알림을 주고 있기때문에 성능면에서도 안좋은 영향을 끼칠것 같습니다.
필요한 UITextView인스턴스에만 프로토콜을 채택하는 방법으로 수정해보면 어떨까요?

2023-11-13 08:51 UTC, f-lab-jercy commented on pins/Extension/UITextView.swift
> +    var textPublisher: AnyPublisher<String, Never> {
UITextView의 텍스트변경을 감지하는 확장으로 보입니다. 하지만 이 확장의 함수명을 봤을때는 해당내용을 알수가 없습니다. 조금더 명확하게 이름을 변경해보면 좋을것 같습니다.
예를들면 textDidChangePublisher와 같이 바꿀수 있을것 같습니다.

2023-11-13 08:51 UTC, f-lab-jercy commented on pins/Service/FirestorageService.swift
> +class FirestorageService {
FirestorageService로 되어 있는데, Firebase Storage를 의미한다면 FirebaseStorageService가 더 적절할 것 같습니다

2023-11-13 08:51 UTC, f-lab-jercy commented on pins/Service/FirestorageService.swift
> +        let imageName = UUID().uuidString + String(Date().timeIntervalSince1970)
이 부분에서 이미지 이름을 생성하고 있는데, 여기서 UUID().uuidString만 사용해도 충분히 유니크한 값이 생성됩니다. Date().timeIntervalSince1970를 추가하는 특별한 이유가 있나요?

2023-11-13 08:51 UTC, f-lab-jercy commented on pins/Service/FirestorageService.swift
> +    }
uploadImages 메소드에서 여러 이미지를 업로드할 때, 각 이미지 업로드가 독립적으로 수행될 수 있도록 DispatchGroup을 사용하고 있는데, 이 방법은 효율적입니다. 그러나 여기서 업로드된 이미지의 URL들이 원본 이미지 배열과 동일한 순서로 반환되는 것을 보장할 수 있나요? 순서가 중요하다면 이를 보장하는 방법을 고려해야 합니다.

2023-11-13 08:51 UTC, f-lab-jercy commented on pins/Service/FirestorageService.swift
> +    }()
private static let metaData: StorageMetadata를 통해 메타데이터를 설정하고 있는데, 현재는 "image/jpeg" 유형만을 처리하고 있습니다. 다양한 이미지 형식을 처리할 수 있도록 확장성을 고려해 볼 필요가 있습니다. 예를 들어, 이미지 형식에 따라 적절한 메타데이터를 설정하는 로직을 추가할 수 있습니다.

2023-11-13 08:51 UTC, f-lab-jercy commented on pins/Service/FirestorageService.swift
> +class FirestorageService {
이 클래스의 모든 메소드가 static으로 선언되어 있어 실제로 인스턴스를 생성할 필요가 없어 보입니다. enum형태로 만들어보는건 어떨까요?

2023-11-13 08:51 UTC, f-lab-jercy commented on pins/ViewModel/CreateViewModel.swift
> +        CLLocation(latitude: longitude, longitude: latitude)
latitude와 longitude가 뒤바껴있는데 혹시 의도하신걸까요?

2023-11-14 05:07 UTC, MojitoBar commented on pins/ViewModel/CreateViewModel.swift
> +        CLLocation(latitude: longitude, longitude: latitude)
헉 잘못 적은게 맞습니다!

2023-11-14 05:15 UTC, MojitoBar commented on pins/Extension/Date.swift
> +    func now() -> String {
함수 명을 좀 더 알아보기 쉽게 currentDateTimeAsString로 변경했습니다!

2023-11-14 06:23 UTC, MojitoBar commented on pins/Extension/UITextView.swift
> +extension UITextView {
```swift
protocol TextPublisher {
    var textDidChangePublisher: AnyPublisher<String, Never> { get }
}
```

프로토콜을 만들고 CustomTextView에 채택하는 방식으로 수정해봤습니다!
특정 인스턴스에만 프로토콜을 채택하는 방식으로 수정해보려 했는데, 적당한 방법을 찾지 못했습니다 .. 혹시 더 좋은 방법이 있을까요?

2023-11-14 06:42 UTC, MojitoBar commented on pins/Service/FirestorageService.swift
> +        let imageName = UUID().uuidString + String(Date().timeIntervalSince1970)
UUID().uuidString은 RFC 4122 버전 4의 랜덤값을 이용해서 UUID를 생성한다고 알고있습니다!
따라서 정말 낮은 확률이지만 중복될 가능성이 전혀 없지는 않다고 판단해서 시간 정보를 더해주었습니다.
하지만 좀 더 확인해보니,
`중복 발생 확률을 구해보면 UUID v4는 초당 100만개의 ID를 100년동안 생성 할 시, 약 0.00009% 확률로 중복이 발생합니다.`
시간 정보를 사용하지 않아도 충분히 유니크한 값을 생성할 수 있을 것 같아 제거해도 될 것 같습니다.

참고한 블로그 링크 입니다!

- [swift uuid](https://medium.com/@jang.wangsu/ios-swift-uuid%EB%8A%94-%EC%96%B4%EB%96%A4-%EC%9B%90%EB%A6%AC%EB%A1%9C-%EB%A7%8C%EB%93%A4%EC%96%B4%EC%A7%80%EB%8A%94-%EA%B2%83%EC%9D%BC%EA%B9%8C-22ec9ff4e792)
- [uuid 중복 확률](https://cochori.com/uuid-%EC%A4%91%EB%B3%B5-%ED%99%95%EB%A5%A0/#:~:text=%EC%A4%91%EB%B3%B5%20%EB%B0%9C%EC%83%9D%20%ED%99%95%EB%A5%A0%EC%9D%84%20%EA%B5%AC%ED%95%B4,%EB%A1%9C%20%EC%A4%91%EB%B3%B5%EC%9D%B4%20%EB%B0%9C%EC%83%9D%ED%95%A9%EB%8B%88%EB%8B%A4.)

2023-11-14 06:55 UTC, MojitoBar commented on pins/Service/FirestorageService.swift
> +    }()
```swift
private static func metaData(for image: UIImage) -> StorageMetadata {
    let metaData = StorageMetadata()
    metaData.contentType = mimeType(for: image)
    return metaData
}

private static func mimeType(for image: UIImage) -> String {
    if let _ = image.pngData() {
        return "image/png"
    } else if let _ = image.jpegData(compressionQuality: 1.0) {
        return "image/jpeg"
    } else {
        return "application/octet-stream"
    }
}
```

mimeType을 동적으로 결정할 수 있게끔 수정했습니다!
필요에 따라 다른 이미지 형식을 지원해야 한다면 `mimeType(for image:)` 메서드를 수정해서 문제를 해결할 수 있게 했습니다.

2023-11-16 08:50 UTC, MojitoBar commented
남겨주신 코멘트와 멘토링때 리뷰해주신 부분 기억나는대로 모두 반영했습니다 !
혹시 빠진 부분 있다면 알려주시면 감사드립니다 🙇‍♂️

- 현재 날짜 구하는 함수명을 좀 더 명확하게 수정했습니다. & localization을 위해 dateStyle과 timeStyle을 적용했습니다.
- 이미지를 여러개 업로드할 때 순서를 보장하게 수정했습니다.
  -  맨 처음 이미지를 로드할 때 인덱스 정보를 같이 담아서 로드한 후 url을 서버에 저장할 때는 인덱스 순으로 정렬하여 저장했습니다.
- 이미지의 확장자 정보를 가져오는 로직을 수정했습니다.
  - 이미지를 로드할 때 확장자 정보를 파일 url로 부터 받아오는 방식으로 수정해서 이미지 별 분기 처리를 할 필요가 없어졌습니다.
- localization 키값을 화면에 그려지는 정보에 맞게 수정했습니다.
- extension 폴더의 파일명을 수정했습니다.
- GCD를 사용하던 코드를 Concurrency 코드로 수정했습니다.

2023-11-20 02:19 UTC, f-lab-jercy commented
잘 해주셨네요! 고생하셨습니다.

2023-11-20 05:57 UTC, merged