전체 리뷰 PR
f-lab-edu/pins pull request #54
Opened 2023-12-21 08:54 UTC by MojitoBar

2023-12-26 07:33 UTC, f-lab-jercy requested changes

2023-12-26 07:33 UTC, f-lab-jercy commented on .gitignore
> +
무의미한 주석이나 gitignore는 제거를 하면 좋을것 같습니다.

2023-12-26 07:33 UTC, f-lab-jercy commented on pins.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
패키지 리졸브 파일의 역할은 무엇이고 이 파일은 커밋을 하는게 좋을까요?

2023-12-26 07:33 UTC, f-lab-jercy commented on pins/Application/AppDelegate.swift
> +        // Use this method to release any resources that were specific to the discarded scenes, as they will not return.
여기도 불필요한 주석이나 사용하지 않는 delegate는 제거하는것이 좋습니다.

2023-12-26 07:33 UTC, f-lab-jercy commented on pins/Application/SceneDelegate.swift
> +//
불필요한 주석은 제거 해 주세요.

2023-12-26 07:33 UTC, f-lab-jercy commented on pins/Application/SceneDelegate.swift
> +        }
개인적으로는 이런 코드에서는 3항연산자를 주로 사용하는 편입니다. 3항연산자는 어떠신가요?

`let viewController: UIViewController = isAuthenticated ? MainViewController : LoginViewController()`

swift 최신 문법으로는 아래와 같은 형태로도 가능합니다.
```
let viewController: UIViewController = if is Authenticated {
    return MainViewController()
} else {
    return LoginViewController()
}
```

2023-12-26 07:33 UTC, f-lab-jercy commented on pins/Data/Repository/FirebaseRepository.swift
> +            }
https://github.com/firebase/firebase-ios-sdk/pull/11289

firebase자체적으로 async await를 지원하도록 7개월전에 만들어져있는것으로 보입니다. 이렇게 직접 withCheckedContinuation을 사용하지말고 만들어져 있는 async await를 이용하면 더 좋을것 같습니다.

2023-12-26 07:33 UTC, f-lab-jercy commented on pins/Data/Repository/UserRepository.swift
> +            fatalError("Error getting documents: \(error.localizedDescription)")
catch에서 fatalError를 이용하는것보다 해당 함수에서 throws로 에러를 전달해주고, getUser를 호출한쪽에서 유저를 가져오지 못했을떄 어떻게 처리를 하면 좋을지를 검토 하면 좋을것 같습니다.

2023-12-26 07:33 UTC, f-lab-jercy commented on pins/Data/Service/FirestorageService.swift
> +        return urls
uploadImages 함수에서 이미지 업로드를 순차적으로 처리하고 있어 효율성이 떨어질 수 있습니다.
async let 또는 TaskGroup을 찾아보세요.

2023-12-26 07:33 UTC, f-lab-jercy commented on pins/Data/Service/UserService.swift
> +            return nil
서비스에서는 nil을 리턴하기보단 throws로 명확한 에러를 리턴해주는것이 더 좋아보입니다.
이 위의 다른 서비스들에서도 fatalError를 처리하거나 한 부분들은 동일합니다.

2023-12-26 07:33 UTC, f-lab-jercy commented on pins/Data/Service/UserService.swift
> +    }
putUser는 비동기 처리가 고려되어있지않은데 추후에 처리에 용이하게 만들기 위해서 async로 변경하면 좋아 보입니다.

2023-12-26 07:33 UTC, f-lab-jercy commented on pins/Domain/Entity/PinResponse.swift
> +    var images: [UIImage] = []
response에 uiimage 자체를 저장하고 있는데
UIImage를 사용하기 위해서 UIKit객체를 response가 들고있는것이 좋을까요?
굳이 필요가 없다면 Data형태로 변경하는것도 좋은 방법일수 있습니다.

2023-12-26 07:33 UTC, f-lab-jercy commented on pins/Domain/UseCase/DetailUseCase.swift
> +        }
여기도 위와 동일한 for문안에서의 await가 있습니다.

2023-12-26 07:33 UTC, f-lab-jercy commented on pins/Domain/UseCase/LoginUseCase.swift
> +            return .failure(NSError(domain: "LoginError: \(error)", code: -1, userInfo: nil))
Objective-C에서 에러를 처리할 필요가 없다면 NSError대신에 직접 Error프로토콜을 채택해서 사용하는것이 더 좋습니다.

2023-12-26 07:33 UTC, f-lab-jercy commented on pins/Domain/UseCase/LoginUseCase.swift
> +                return .success(UserResponse(user: userResult, image: profileImage, firstTime: false))
성능적인 부분으로 생각해봤을때 프로파일이미지는 로그인처리에 있어서 꼭 필요한 정보라기보단, 추후에 다운로드해와도 좋을것 같은데 꼭 이렇게 await로 할 필요가 있을까요?

2023-12-26 07:33 UTC, f-lab-jercy commented on pins/Extension/CALayer+Extensions.swift
> +    }
일반적인 상황은 아니여서 한번 생각만 해봐도 좋을것 같습니다.
CALayer의 frame 크기가 변경될 수 있는 경우(예: 뷰의 크기가 동적으로 변하는 경우), 추가된 테두리가 올바르게 표시되지 않을 수 있어 보입니다.

어떻게 해 볼 수 있을까요?

2023-12-26 07:33 UTC, f-lab-jercy commented on pins/Extension/String+Extensions.swift
> +        let dateFormatter = DateFormatter()
자주 사용되는 포맷터의 경우, static 인스턴스를 사용하거나 싱글턴 패턴을 사용하여 퍼포먼스를 최적화할 수 있습니다.

2023-12-26 07:33 UTC, f-lab-jercy commented on pins/Presentation/Animation/AnimationManager.swift
> +class AnimationManager {
이 내용을 상속받지 않는다면 final class로 선언해두면 좋아보입니다.

2023-12-26 07:33 UTC, f-lab-jercy commented on pins/Presentation/View/Common/CustomButton.swift
> +    }
앱이 켜져있는 상태에서 다크모드를 변경했을때 border는 기존의 모드의 컬러로 적용이 되어있고 새로운 모드의 컬러로 변경이 안되는 문제가 있을수 있습니다.

이를 어떻게 해결 할 수 있을까요?

2023-12-26 07:35 UTC, f-lab-jercy commented on pins/Presentation/View/DetailView/CommentView.swift
> +    }
layout을 잡는 영역은 updateConstraints라는 함수안에 들어가도록 하면 좋습니다.
https://developer.apple.com/documentation/uikit/uiview/1622512-updateconstraints

2023-12-26 07:35 UTC, f-lab-jercy commented on pins/Presentation/View/DetailView/CommentView.swift
> +    }
https://velog.io/@dev-yong/WWDC-High-Performance-Auto-Layout

2023-12-28 10:26 UTC, MojitoBar commented on pins/Presentation/View/Common/CustomButton.swift
> +    }
```swift
override func traitCollectionDidChange(_ previousTraitCollection: UITraitCollection?) {
    super.traitCollectionDidChange(previousTraitCollection)

    if traitCollection.hasDifferentColorAppearance(comparedTo: previousTraitCollection) {
        setBorder(width: layer.borderWidth, color: UIColor.label.cgColor)
    }
}
```

이런식으로 화면 모드가 변경될 때를 감지해 border 색을 업데이트 해줄 수 있습니다 !

2023-12-31 07:57 UTC, MojitoBar commented on .gitignore
> +
bfd8f280e3bf1d107715403f43b5660ba6735379

2023-12-31 07:57 UTC, MojitoBar commented on pins/Application/AppDelegate.swift
> +        // Use this method to release any resources that were specific to the discarded scenes, as they will not return.
5996f9c3c10bb9de2dc8e896ccc6cd1b242b5603

2023-12-31 07:57 UTC, MojitoBar commented on pins/Application/SceneDelegate.swift
> +        }
5996f9c3c10bb9de2dc8e896ccc6cd1b242b5603

2023-12-31 07:59 UTC, MojitoBar commented on pins/Data/Repository/UserRepository.swift
> +            fatalError("Error getting documents: \(error.localizedDescription)")
64e87feaf2317494408b7e00ebe94aa50b395946

fatalError 대신 Error를 던지게 수정했습니다!
사용자에게 어떤 메시지를 표시할지는 아직 적용하지 못했습니다.

2023-12-31 07:59 UTC, MojitoBar commented on pins/Data/Service/FirestorageService.swift
> +        return urls
972aa8ee5a4a1a645e8a5f662058544c27d3d524

2023-12-31 07:59 UTC, MojitoBar commented on pins/Data/Service/UserService.swift
> +            return nil
192e7c9c64cda5fa55d41632ab810915e5b692c8
5a502bb8907d061f8bd3cbb8d7874d5a63f64214

서비스에서 전보다 명확한 에러를 리턴하게끔 수정했습니다 !

2023-12-31 08:00 UTC, MojitoBar commented on pins/Data/Service/UserService.swift
> +    }
f89a89d470c415d3505bf6e0a8d06e82101e87e8

2023-12-31 08:00 UTC, MojitoBar commented on pins/Presentation/Animation/AnimationManager.swift
> +class AnimationManager {
15f6c4a87a614d4500caba622c1dc99f50e5a785

2023-12-31 08:00 UTC, MojitoBar commented on pins/Extension/String+Extensions.swift
> +        let dateFormatter = DateFormatter()
1ae4910451fe9abd738435c3578c70c4bc281bed

2023-12-31 08:01 UTC, MojitoBar commented on pins/Domain/Entity/PinResponse.swift
> +    var images: [UIImage] = []
700f9db3577750bd5e87ac24f5f8cce14b0406f6

2023-12-31 08:01 UTC, MojitoBar commented on pins/Domain/UseCase/DetailUseCase.swift
> +        }
c77117e265101c28df32b6f172cb93d2177201be

2023-12-31 08:01 UTC, MojitoBar commented on pins/Domain/UseCase/LoginUseCase.swift
> +            return .failure(NSError(domain: "LoginError: \(error)", code: -1, userInfo: nil))
de9e9735b852cb2ff571ccfdff944141d440d2bb

2024-01-03 12:44 UTC, closed without merging